home: improve documentation

diff --git a/home/bash_aliases b/home/bash_aliases
--- a/home/bash_aliases
+++ b/home/bash_aliases
@@ -35,11 +35,11 @@ load-group() {
 which()   { builtin type -P "$@" ; }
 sprunge() { local l=${2-bash}; echo $(curl -sSF "sprunge=<${1:--}" http://sprunge.us)${l:+?$l}${3:+#n-$3}; }
 
-# Take a look at realpath --relative-to=DIR
+# Take a look at realpath --relative-to=DIR and ln -r|--relative
 relpath() { python3 -c "import os,sys;print(os.path.relpath(*sys.argv[1:3]))" "$@"; }
 
 # Set the window title of the terminal emulator
-# Also available as 'xtitle' apt package
+# Also available as 'xtitle' apt package, and in bash_aliases_min (sans documentation)
 # Empty arguments are ignored by xterm and reset default title in Gnome Terminal
 xtitle() {
 	# tput hs && {[[ "$1" ]] && {tput tsl; printf '%s' "$*"; tput fsl; } || tput dsl; }
@@ -64,13 +64,13 @@ newopen() {
 	for arg in "$@"; do
 		if [[ "$arg" == '--' ]]; then break; fi
 		if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
-			printf "Open a FILE with default application\n${usage}"
+			printf "Open FILE (or URI) with its default application\n${usage}"
 			return
 		fi
 	done
 	# TODO: proper arg parse to allow --, -v|--verbose, -q|--quiet
 	if [[ -z "$f" ]]; then
-		printf >&2 "open: missing FILE argument\n${usage}"
+		printf >&2 "open: missing FILE/URI argument\n${usage}"
 		return 1
 	fi
 
