unify non-compliant XDG software handling

diff --git a/home/bash_aliases_min b/home/bash_aliases_min
--- a/home/bash_aliases_min
+++ b/home/bash_aliases_min
@@ -16,6 +16,51 @@ export LANGUAGE=en_US:en
 export LC_ALL=en_US.UTF-8
 export LC_NUMERIC=pt_BR.UTF-8  # might require sudo locale-gen pt_BR.UTF-8
 
+# >>>>> XDG defs <<<<<----------------------------------------------------------
+
+xdg_config=${XDG_CONFIG_HOME:-$HOME/.config}
+xdg_data=${XDG_DATA_HOME:-$HOME/.local/share}
+xdg_cache=${XDG_CACHE_HOME:-$HOME/.cache}
+
+# >>>>> XDG profile <<<<<-------------------------------------------------------
+
+# gnupg
+export GNUPGHOME=${xdg_config}/gnupg
+
+# Not yet implemented on 3.8: https://bugs.python.org/issue29779
+export PYTHONHISTORY=${XDG_CONFIG_HOME:-$HOME/.config}/python_history  # or /python/history
+
+# IPython/Jupiter
+# Both already used XDG_CONFIG_HOME for a while, then reverted :-(
+# https://github.com/jupyter/notebook/issues/2374
+# https://github.com/ipython/ipython/issues/48
+export IPYTHONDIR=${xdg_config}/ipython
+export JUPYTER_CONFIG_DIR=${xdg_config}/jupyter
+
+# PyLint
+# https://github.com/PyCQA/pylint/issues/1364
+export PYLINTHOME=${xdg_cache}/pylint   # Default ~/.pylint.d/
+export PYLINTRC=${xdg_config}/pylintrc  # Default ~/.pylintrc
+
+# Pipx
+export PIPX_HOME=${xdg_data}/pipx  # Default ~/.local/pipx
+
+# Some non-compliant software only use XDG_{CONFIG,DATA}_HOME if it exists
+for xdg_path in "$xdg_config" "$xdg_data"; do
+	if ! [ -d "$xdg_path" ]; then
+		mkdir --parents --mode 700 -- "$xdg_path"
+	fi
+done
+
+# >>>>> XDG bashrc <<<<<--------------------------------------------------------
+
+alias wget="wget --hsts-file=${xdg_config}/wget-hsts"
+
+# https://github.com/dustinkirkland/byobu/pull/57
+if exists byobu && ! [[ -d "${xdg_data}/byobu" ]]; then
+	mkdir -p -- "${xdg_data}/byobu"
+fi
+
 # >>>>> Aliases <<<<<-----------------------------------------------------------
 
 # SP  ' '  0x20 = · U+00B7 Middle Dot
@@ -176,7 +221,6 @@ complete -F _comp_pkg_names ubuntu-package why  # packages in repositories
 complete-copy ls ll la
 complete-copy dwww-man mand package
 
-
 # >>>>> PS1 customization <<<<<-------------------------------------------------
 # http://bashrcgenerator.com/
 
@@ -236,8 +280,6 @@ PS1=${c[RESET]}${c[BOLD]}\
 "${c[RED]}\$(__git_ps1 '%s ')${c[YELLOW]}\$(_format_exitcode)${c[BLUE]}\\$ "\
 ${c[RESET]}
 
-unset color c
-
 # >>>>> Settings <<<<<----------------------------------------------------------
 
 # Disable the dreaded history expansion for interactive sessions
@@ -255,16 +297,16 @@ paths=(
 for path in "${paths[@]}"; do
 	if [[ -r "$path" ]]; then source "$path"; fi
 done
-unset paths path
 
-if !((BASH_STARTUP)); then unset BASH_STARTUP; return; fi; unset BASH_STARTUP
+# >>>> Cleanup <<<<<------------------------------------------------------------
+
+unset xdg_{home,config,cache,path}
+unset color c
+unset paths path
 
 # >>>>> Startup commands <<<<<--------------------------------------------------
 
-# https://github.com/dustinkirkland/byobu/pull/57
-if exists byobu && ! [[ -d "${XDG_DATA_HOME:-$HOME/.local/share}/byobu" ]]; then
-	mkdir -p -- "${XDG_DATA_HOME:-$HOME/.local/share}/byobu"
-fi
+if !((BASH_STARTUP)); then unset BASH_STARTUP; return; fi; unset BASH_STARTUP
 
 # So useful!
 if exists neofetch; then neofetch; fi
