home: reorganize and sync functions and aliases for upcoming snipfile()

diff --git a/home/bash_aliases b/home/bash_aliases
--- a/home/bash_aliases
+++ b/home/bash_aliases
@@ -8,22 +8,11 @@ alias whitespace="sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g'"
 alias ls="ls --color=auto --group-directories-first -1"
 alias ll="ls -l --time-style=long-iso"
 alias la="ll -A"
-alias cd..="cd .."
-alias cd...="cd ../.."
-alias cd....="cd ../../.."
-alias cd.....="cd ../../../.."
-alias ..="cd .."
-alias ...="cd ../.."
-alias ....="cd ../../.."
-alias .....="cd ../../../.."
 alias path="echo \$PATH"
 alias fstab="sudo nano /etc/fstab"
 alias open="xdg-open"
-alias trash="trash-put"  # requires trash-cli package
-#alias rm="trash"  # affects other aliases and funcions
-alias mand="dwww-man"
-alias package="dpkg-www"
-alias ca="CA.pl"
+alias trash="trash-put"  # requires trash-cli. Do NOT alias rm, affects functions
+alias mand="dwww-man"    # requires dwww
 alias dd-progress="dd status=progress bs=1M iflag=count_bytes"
 alias dd-nocache="dd-progress oflag=nocache,sync"
 alias dfd='df -H -x tmpfs -x squashfs -x devtmpfs'
@@ -33,75 +22,23 @@ alias rot13="tr 'A-Za-z' 'N-ZA-Mn-za-m'"
 alias json='python3 -m json.tool'  # 'jq' is a beter alternative, if installed
 alias why='apt rdepends --installed'  # can also be 'aptitude why'
 alias dmesg="dmesg --follow"  # welcome 2021!
-#alias have="exists"
-
-#alias find-newer='find . -type f -newermt'  # '10 days ago'
-find-newer(){ find "${2:-.}" -type f -newermt "$1" -exec ls -lrt "{}" +; }
-
-where() { dpkg --search -- $(type -p "${1:-}"); }
-ubuntu-package() { open "http://packages.ubuntu.com/search?searchon=names&suite=all&section=all&keywords=$1"; }
 
 try()     { "$@" 2>/dev/null || :; }
+where()   { dpkg --search -- $(type -p "${1:-}"); }
 cdl()     { cd "$@" && ll ; }
 md()      { mkdir "$@" && cd "${@: -1}" ; }
-which()   { builtin type -P "$@" ; }
-sprunge() { local l=${2-bash}; echo $(curl -sSF "sprunge=<${1:--}" http://sprunge.us)${l:+?$l}${3:+#n-$3}; }
 compile() { gcc -Wall -Wextra -o "${1%.*}" "$@"; }
-relpath() { python3 -c "import os,sys;print(os.path.relpath(*sys.argv[1:3]))" "$@"; }
 
 _datefmt()  { [[ "$2" ]] && d=(-d"${3:-}${2}") || d=(); date "$1" "${d[@]}"; }
 now()       { _datefmt '--rfc-3339=seconds' "${1:-}" '@'; }
 timestamp() { _datefmt '+%Y%m%d%H%M%S'      "${1:-}" '@'; }
 epoch()     { _datefmt '+%s'                "${1:-}"; }
 
+ubuntu-package() { open "http://packages.ubuntu.com/search?searchon=names&suite=all&section=all&keywords=$1"; }
+
 cmdlist() { type -a "$1"; ll "$(type -P "$1")" ; }
 cmdcat()  { cat  "$(type -P "$1")" ; }
 cmdopen() { open "$(type -P "$1")" ; }
-
-# Set the window title of the terminal emulator
-# Also available as 'xtitle' apt package
-# Empty arguments are ignored by xterm and reset default title in Gnome Terminal
-xtitle() {
-	# tput hs && {[[ "$1" ]] && {tput tsl; printf '%s' "$*"; tput fsl; } || tput dsl; }
-	# But using tput only works with hs-capable TERM, e.g. xterm+sl{,-twm}
-	# xterm can save/restore title with '\e[22;0t' / '\e[23;0t'
-	# See man 5 terminfo / https://invisible-island.net/ncurses/terminfo.ti.html
-	# https://gist.github.com/KevinGoodsell/744284
-	# http://ncurses.scripts.mit.edu/?p=ncurses.git;a=blob;f=misc/terminfo.src;hb=HEAD
-	printf '\e]2;%s\a' "$*"
-}
-
-# WIP to be the new open()
-# idea: supress error messages only *after* (and *if*) successfully opened a file
-# all messages before from launcher itself (gio open/xdg-open) should be printed
-# after launcher returns, everything else should be discarded or redirected
-# If needed, test for success likelihood: file/URI exists, has default handler, etc
-newopen() {
-	local f=${1:-}
-	local out="$HOME"/.nohup.txt
-	local usage="Usage: open [-h|--help] FILE\n" arg err
-
-	for arg in "$@"; do
-		if [[ "$arg" == '--' ]]; then break; fi
-		if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
-			printf "Open a FILE with default application\n${usage}"
-			return
-		fi
-	done
-	# TODO: proper arg parse to allow --, -v|--verbose, -q|--quiet
-	if [[ -z "$f" ]]; then
-		printf >&2 "open: missing FILE argument\n${usage}"
-		return 1
-	fi
-
-	# now dance around with gio mime, gio info, gio open, xdg-mime, xdg-open
-	if ! { xdg-open "$f" &>>"$out" || { err=$?; false; }; }; then
-		exec >&2
-		#echo "error opening '$f', see $out"
-		tail -n1 "$out"
-		return $err
-	fi
-}
 
 apt-list-manual() {
 	# https://askubuntu.com/a/492343/11015
@@ -165,9 +102,74 @@ dump-system-data() {
 	try dconf dump /                          > "$target"/dconf.txt
 	try cat /etc/fstab                        > "$target"/fstab.txt
 	try cat /etc/apt/sources.list{,.d/*.list} > "$target"/apt-sources.txt
-	try crontab --list                        > "$target"/crontab.txt
+	try crontab -l                            > "$target"/crontab.txt
 	apt-list-manual "$2"                      > "$target"/apt-packages.txt
 	try sudo fdisk --list                     > "$target"/fdisk.txt
+}
+
+alias cd..="cd .."
+alias cd...="cd ../.."
+alias cd....="cd ../../.."
+alias cd.....="cd ../../../.."
+alias ..="cd .."
+alias ...="cd ../.."
+alias ....="cd ../../.."
+alias .....="cd ../../../.."
+alias package="dpkg-www"  # requires dpkg-www
+alias ca="CA.pl"
+#alias have="exists"
+#alias find-newer='find . -type f -newermt'  # '10 days ago'
+find-newer(){ find "${2:-.}" -type f -newermt "$1" -exec ls -lrt "{}" +; }
+
+which()   { builtin type -P "$@" ; }
+sprunge() { local l=${2-bash}; echo $(curl -sSF "sprunge=<${1:--}" http://sprunge.us)${l:+?$l}${3:+#n-$3}; }
+
+# Take a look at realpath --relative-to=DIR
+relpath() { python3 -c "import os,sys;print(os.path.relpath(*sys.argv[1:3]))" "$@"; }
+
+# Set the window title of the terminal emulator
+# Also available as 'xtitle' apt package
+# Empty arguments are ignored by xterm and reset default title in Gnome Terminal
+xtitle() {
+	# tput hs && {[[ "$1" ]] && {tput tsl; printf '%s' "$*"; tput fsl; } || tput dsl; }
+	# But using tput only works with hs-capable TERM, e.g. xterm+sl{,-twm}
+	# xterm can save/restore title with '\e[22;0t' / '\e[23;0t'
+	# See man 5 terminfo / https://invisible-island.net/ncurses/terminfo.ti.html
+	# https://gist.github.com/KevinGoodsell/744284
+	# http://ncurses.scripts.mit.edu/?p=ncurses.git;a=blob;f=misc/terminfo.src;hb=HEAD
+	printf '\e]2;%s\a' "$*"
+}
+
+# WIP to be the new open()
+# idea: supress error messages only *after* (and *if*) successfully opened a file
+# all messages before from launcher itself (gio open/xdg-open) should be printed
+# after launcher returns, everything else should be discarded or redirected
+# If needed, test for success likelihood: file/URI exists, has default handler, etc
+newopen() {
+	local f=${1:-}
+	local out="$HOME"/.nohup.txt
+	local usage="Usage: open [-h|--help] FILE\n" arg err
+
+	for arg in "$@"; do
+		if [[ "$arg" == '--' ]]; then break; fi
+		if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
+			printf "Open a FILE with default application\n${usage}"
+			return
+		fi
+	done
+	# TODO: proper arg parse to allow --, -v|--verbose, -q|--quiet
+	if [[ -z "$f" ]]; then
+		printf >&2 "open: missing FILE argument\n${usage}"
+		return 1
+	fi
+
+	# now dance around with gio mime, gio info, gio open, xdg-mime, xdg-open
+	if ! { xdg-open "$f" &>>"$out" || { err=$?; false; }; }; then
+		exec >&2
+		#echo "error opening '$f', see $out"
+		tail -n1 "$out"
+		return $err
+	fi
 }
 
 # Profiling:
diff --git a/home/bash_aliases_min b/home/bash_aliases_min
--- a/home/bash_aliases_min
+++ b/home/bash_aliases_min
@@ -29,8 +29,8 @@ alias la="ll -A"
 alias path="echo \$PATH"
 alias fstab="sudo nano /etc/fstab"
 alias open="xdg-open"
-alias trash="trash-put"  # requires trash-cli package
-alias rm="trash"
+alias trash="trash-put"  # requires trash-cli. Do NOT alias rm, affects functions
+alias mand="dwww-man"    # requires dwww
 alias dd-progress="dd status=progress bs=1M iflag=count_bytes"
 alias dd-nocache="dd-progress oflag=nocache,sync"
 alias dfd='df -H -x tmpfs -x squashfs -x devtmpfs'
@@ -39,14 +39,13 @@ alias dud='lsblk --exclude 7'  # 7 = loop devices, most likely snaps
 alias rot13="tr 'A-Za-z' 'N-ZA-Mn-za-m'"
 alias json='python3 -m json.tool'  # 'jq' is a beter alternative, if installed
 alias why='apt rdepends --installed'  # can also be 'aptitude why'
+alias dmesg="dmesg --follow"  # welcome 2021!
 
-exists()  { type "$@" &>/dev/null; }
+try()     { "$@" 2>/dev/null || :; }
 where()   { dpkg --search -- $(type -p "${1:-}"); }
 cdl()     { cd "$@" && ll ; }
 md()      { mkdir "$@" && cd "${@: -1}" ; }
 compile() { gcc -Wall -Wextra -o "${1%.*}" "$@"; }
-dmesgw()  { watch -n 0.25 "dmesg $@ | tail -n $((LINES-3))"; }
-xtitle()  { printf '\e]2;%s\a' "$*"; }
 
 _datefmt()  { [[ "$2" ]] && d=(-d"${3:-}${2}") || d=(); date "$1" "${d[@]}"; }
 now()       { _datefmt '--rfc-3339=seconds' "${1:-}" '@'; }
@@ -58,6 +57,42 @@ ubuntu-package() { open "http://packages.ubuntu.com/search?searchon=names&suite=
 cmdlist() { type -a "$1"; ll "$(type -P "$1")" ; }
 cmdcat()  { cat  "$(type -P "$1")" ; }
 cmdopen() { open "$(type -P "$1")" ; }
+
+apt-list-manual() {
+	# https://askubuntu.com/a/492343/11015
+	local manifest=${1:-}
+	local initial=/var/log/installer/initial-status.gz
+	local list=
+	# User-provided manifest, assume same format as https://releases.ubuntu.com
+	if [[ "$manifest" ]]; then
+		list=$(awk '{print $1}' "$manifest") || {
+			echo "Usage: apt-list-manual [MANIFEST-FILE]" >&2
+			return
+		}
+	# List from system installer log
+	elif [[ -f "$initial" ]]; then
+		list=$(gzip -dc "$initial" | sed -n 's/^Package: //p')
+	fi
+
+	# List packages
+	comm -23 <(apt-mark showmanual | sort -u) <(echo "$list" | sort -u)
+
+	# If initial log not found and no manifest provided, show download instructions
+	if [[ "$list" ]]; then
+		return
+	fi
+	printf 'ERROR:' >&2
+
+	# numeric version including with point release: 20.04.3
+	local version=$(awk -F'="?| ' '/^VERSION=/{print $2}' /etc/*release)
+	local msg=(
+		"Empty or missing manifest file: ${manifest:-$initial}"
+		"Is this a server? Without a manifest the above list is not accurate."
+		"Download it from: http://releases.ubuntu.com/${version}/"
+		"And try again with: apt-list-manual MANIFEST-FILE"
+	)
+	printf '\t%s\n' "${msg[@]}" >&2
+}
 
 install_packages() {
 	# Avoid marking installed packages as manual by only installing missing ones
@@ -77,6 +112,24 @@ package_installed() {
 	local ok
 	ok=$(package_version "$1") && [[ "$ok" ]]
 }
+
+dump-system-data() {
+	local target=${1:-./system-data}
+	local manifest=${2:-}
+	mkdir -p -- "$target"
+	try dconf dump /                          > "$target"/dconf.txt
+	try cat /etc/fstab                        > "$target"/fstab.txt
+	try cat /etc/apt/sources.list{,.d/*.list} > "$target"/apt-sources.txt
+	try crontab -l                            > "$target"/crontab.txt
+	apt-list-manual "$2"                      > "$target"/apt-packages.txt
+	try sudo fdisk --list                     > "$target"/fdisk.txt
+}
+
+# Other aliases <<<<<----------------------------------------------------------
+
+exists()  { type "$@" &>/dev/null; }
+xtitle()  { printf '\e]2;%s\a' "$*"; }
+snipfile(){ local n=${3:-5}; awk "/${2:-} *>{${n}}/,/<{${n}}/" "${1:-}"; }
 
 # 1337!
 matrix() {
@@ -121,7 +174,7 @@ complete-copy dwww-man mand package
 # Alternative: \${?/#0/} directly into PS1, but lacks surrounding spaces
 _format_exitcode() {
 	local s=$?
-	(($s)) && printf "${1:-%s }" "$s"
+	if (($s)); then printf "${1:-%s }" "$s"; fi
 	return $s
 }
 
