home: add a bunch of ShellCheck suggestions and fixes to bash_aliases*

diff --git a/home/bash_aliases b/home/bash_aliases
--- a/home/bash_aliases
+++ b/home/bash_aliases
@@ -1,5 +1,6 @@
 # This is sourced by $SCRIPTS/home/bashrc after it sources $SCRIPTS/home/bash_completion
 
+# shellcheck source=./bash_aliases_min
 source <(snipfile "$SCRIPTS/home/bash_aliases_min" 'Aliases')
 
 # -----------------------------------------------------------------------------
@@ -33,7 +34,8 @@ load-group() {
 } && complete -W "$(groups "${USER:-$(id -un)}" | cut -d: -f2-)" load-group
 
 which()   { builtin type -P "$@" ; }
-sprunge() { local l=${2-bash}; echo $(curl -sSF "sprunge=<${1:--}" http://sprunge.us)${l:+?$l}${3:+#n-$3}; }
+sprunge() { local l=${2-bash};
+	echo "$(curl -sSF "sprunge=<${1:--}" http://sprunge.us)${l:+?$l}${3:+#n-$3}"; }
 
 # Take a look at realpath --relative-to=DIR and ln -r|--relative
 relpath() { python3 -c "import os,sys;print(os.path.relpath(*sys.argv[1:3]))" "$@"; }
@@ -58,7 +60,7 @@ apt-repository-packages() {
 	(($#)) || { echo "Usage: apt-repository-packages REPOSITORY [ARCH]" >&2; return 1; }
 	local filter=$1
 	local arch=${2:-}
-	while IFS= read repo; do
+	while IFS= read -r repo; do
 		echo "$repo" >&2
 		grep '^Package: ' "$repo" | cut -d' ' -f2 | sort -u
 		echo >&2
@@ -78,13 +80,13 @@ newopen() {
 	for arg in "$@"; do
 		if [[ "$arg" == '--' ]]; then break; fi
 		if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
-			printf "Open FILE (or URI) with its default application\n${usage}"
+			printf "Open FILE (or URI) with its default application\n%s" "$usage"
 			return
 		fi
 	done
 	# TODO: proper arg parse to allow --, -v|--verbose, -q|--quiet
 	if [[ -z "$f" ]]; then
-		printf >&2 "open: missing FILE/URI argument\n${usage}"
+		printf >&2 "open: missing FILE/URI argument\n%s" "$usage"
 		return 1
 	fi
 
@@ -119,7 +121,7 @@ pyprofile() {
 pyprofile-view() {
 	(($#)) || { echo "Usage: pyprofile3-view <COMMAND> [ARGS...]" >&2; return 1; }
 	local python=${PYTHON:-python3}
-	local dotfile=pyprofile.$(timestamp).dot
+	local dotfile; dotfile=pyprofile.$(timestamp).dot
 	"$python" -m cProfile -o pyprofile.pstats "$@" &&
 	gprof2dot -f pstats pyprofile.pstats -o "$dotfile" &&
 	xdg-open "$dotfile"
@@ -127,7 +129,8 @@ pyprofile-view() {
 
 venv() {
 	local vdir=${1:-venv}
-	local python=$(compgen -c python | grep -P '^python\d[.\d]*$' | sort -ruV | head -n1)
+	local python
+	python=$(compgen -c python | grep -P '^python\d[.\d]*$' | sort -ruV | head -n1)
 	local usage="Creates a Python Virtual Environment, activate and upgrade it"
 	usage+="\nUsage: venv ENV_DIR"
 	if [[ "$vdir" =~ ^(|-h|--help)$ ]]; then echo -e "$usage" >&2; return 1; fi
@@ -188,7 +191,7 @@ unzip-strip() (
 	local archive=$1
 	local destdir=${2:-}
 	shift; shift || :
-	local tmpdir=$(mktemp -d)
+	local tmpdir; tmpdir=$(mktemp -d)
 	trap 'rm -rf -- "$tmpdir"' EXIT
 	unzip -qd "$tmpdir" -- "$archive"
 	shopt -s dotglob
@@ -219,7 +222,7 @@ matrix() {
 	# cmatrix -a, asynchronous scroll looks bad in linux TTY and terrible in X11
 	# See https://github.com/abishekvashok/cmatrix/issues/124
 	if [[ "$TERM" == "linux" ]]; then
-		local default=$(mktemp) && trap 'rm -f -- "$default"' RETURN
+		local default; default=$(mktemp) && trap 'rm -f -- "$default"' RETURN
 		setfont -O "$default" matrix.psf
 		cmatrix -sbxu8  # -x seems to be -l minus setfont, indicates custom font
 		setfont "$default"
@@ -243,7 +246,7 @@ mv-link() (  # any particular reason for this to be a subshell??? relpath() won'
 )
 
 compare-images() (
-	local tmpdir=$(mktemp -d) || exit 1
+	local tmpdir; tmpdir=$(mktemp -d) || exit 1
 	trap 'rm -rf -- "$tmpdir"' EXIT
 	for img in "$@"; do
 		convert "$img" pam:"$tmpdir"/"$(basename "$img")"
@@ -267,7 +270,7 @@ _minecraft_saverestore() {
 	rm -rf   -- "$dst".bak             &&  # Delete destination backup, if exists
 	mkdir -p -- "$dst"{,.bak}          &&  # Create destination and its backup
 	cp -pr -t   "$dst".bak -- "$dst"/* &&  # Backup destination content
-	rm -rf   -- "$dst"/*               &&  # Delete destination content
+	rm -rf   -- "${dst:?}"/*           &&  # Delete destination content
 	cp -pr -t   "$dst"     -- "$src"/*     # Copy Source content to Destination
 }
 minecraft-save()    { _minecraft_saverestore save;    }
diff --git a/home/bash_aliases_root b/home/bash_aliases_root
--- a/home/bash_aliases_root
+++ b/home/bash_aliases_root
@@ -37,6 +37,7 @@ xdg_create() {
 # Some non-compliant software only use XDG_{CONFIG,DATA,CACHE}_HOME if it exists
 for xdg_path in "$xdg_config" "$xdg_data" "$xdg_cache" "$xdg_state"; do
 	if ! [ -d "$xdg_path" ]; then
+		# shellcheck disable=SC2174
 		mkdir --parents --mode 700 -- "$xdg_path"
 	fi
 done
@@ -84,16 +85,18 @@ unset xdg_create
 
 # >>>>> XDG bashrc <<<<<--------------------------------------------------------
 
+# shellcheck disable=SC2139
 alias wget="wget --hsts-file=${xdg_config}/wget-hsts"
 
 # >>>>> Aliases <<<<<-----------------------------------------------------------
 
 # SP  ' '  0x20 = · U+00B7 Middle Dot
-# TAB '\t' 0x09 = ￫ U+FFEB Halfwidth Rightwards Arrow
+# TAB '\t' 0x09 = ￫ U+FFEB Half width Rightwards Arrow
 # CR  '\r' 0x0D = § U+00A7 Section Sign (⏎ U+23CE also works fine)
 # LF  '\n' 0x0A = ¶ U+00B6 Pilcrow Sign (was "Paragraph Sign")
 alias whitespace="sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g'"
 alias diff="diff -u --color"  # who needs colordiff?
+# shellcheck disable=SC2032
 alias ls="ls --color=auto --group-directories-first -1"
 alias ll="ls -l --time-style=long-iso"
 alias la="ll -A"
@@ -106,7 +109,7 @@ alias dfd='df -H -x tmpfs -x squashfs -x devtmpfs'
 alias duh='du -sbh --si'
 alias dud='lsblk --exclude 7'  # 7 = loop devices, most likely snaps
 alias rot13="tr 'A-Za-z' 'N-ZA-Mn-za-m'"
-alias json='python3 -m json.tool'  # 'jq' is a beter alternative, if installed
+alias json='python3 -m json.tool'  # 'jq' is a better alternative, if installed
 alias why='apt rdepends --installed'  # can also be 'aptitude why'
 alias dmesg="dmesg --follow"  # welcome 2021!
 alias windows-serial="strings /sys/firmware/acpi/tables/MSDM"
@@ -116,6 +119,7 @@ alias 7z-ultra="7z a -mx"  # requires p7zip
 
 # systemd
 for cmd in status start stop restart reload; do
+	# shellcheck disable=SC2139
 	alias "${cmd}=systemctl ${cmd}"
 done
 unset cmd
@@ -123,7 +127,7 @@ unset cmd
 try()     { "$@" 2>/dev/null || :; }
 where()   { dpkg --search -- "$(type -p "$1" || echo "$1")"; }
 cdl()     { cd "$@" && ll ; }
-md()      { mkdir "$@" && cd "${@: -1}" ; }
+md()      { mkdir "$@" && cd "${@: -1}" || return; }
 
 compile()  { gcc -Wall -Wextra -o "${1%.*}" "$@"; }
 gcc-specs(){ gcc -v -xc /dev/null -E -Wp,-v 2>&1; }
@@ -134,7 +138,7 @@ timestamp() { _datefmt '+%Y%m%d%H%M%S'      "${1:-}" '@'; }
 epoch()     { _datefmt '+%s'                "${1:-}"; }
 
 f2b() { local j=${1:-sshd}; sudo fail2ban-client status "$j"; }
-make-parallel() { make -j $(nproc --ignore=2) "$@"; }
+make-parallel() { make -j "$(nproc --ignore=2)" "$@"; }
 
 cmdlist() { type -a "$1"; ll "$(type -P "$1")" ; }
 cmdcat()  { cat  "$(type -P "$1")" ; }
@@ -147,6 +151,7 @@ find-newer(){
 		echo "Usage: find-newer DATE_SPEC [PATH]  # '10 days ago'" >&2
 		return 1
 	fi
+	# shellcheck disable=SC2033
 	find "${2:-.}" -type f -newermt "$1" -exec ls -lrt "{}" +;
 }
 
@@ -160,8 +165,8 @@ delete-duplicate-files() {
 
 manc() {
 	# inspired by https://www.howtogeek.com/683134/
-	local reset=$(tput sgr0)
-	local bold=$(tput bold)
+	local reset; reset=$(tput sgr0)
+	local bold;  bold=$(tput bold)
 	# md=Bold: bold blue (4)
 	# us=Italic/Underline: bold bright yellow (8 + 1 + 2 = 11)
 	# so=Standout (search, prompt): black (0) on white (4 + 2 + 1 = 7)
@@ -223,7 +228,7 @@ apt-list-manual() {
 	printf 'ERROR:' >&2
 
 	# numeric version including with point release: 20.04.3
-	local version=$(awk -F'="?| ' '/^VERSION=/{print $2}' /etc/*release)
+	local version; version=$(awk -F'="?| ' '/^VERSION=/{print $2}' /etc/*release)
 	local msg=(
 		"Empty or missing manifest file: ${manifest:-$initial}"
 		"Is this a server? Without a manifest the above list is not accurate."
@@ -274,7 +279,7 @@ backup-simple() {
 	for arg in "$@"; do
 		if [[ "$arg" == '--' ]]; then break; fi
 		if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
-			printf "Simple backup with rsync\n${usage}\n" >&2; return
+			printf "Simple backup with rsync\n%s\n" "$usage" >&2; return
 		fi
 	done
 	while (($#)); do
@@ -287,7 +292,7 @@ backup-simple() {
 	done
 	args+=( "$@" )
 	if (( ${#args[@]} != 2 )) || [[ -z "${args[0]}" ]] || [[ -z "${args[1]}" ]]; then
-		printf "error: invalid or missing arguments\n${usage}\n" >&2
+		printf "error: invalid or missing arguments\n%s\n" "$usage" >&2
 		return 1
 	fi
 	local source=${args[0]}
@@ -320,7 +325,7 @@ backup-simple() {
 	#--inplace                update destination files in-place (conflicts with --sparse)
 	#--progress               show progress during transfer (implies --verbose)
 	#	--info=flist2,name,progress
-	local cmd=(
+	local cmdarr=(
 		rsync -axS --info=progress2 --no-inc-recursive
 		--exclude='lost+found'
 		#--exclude='.Trash*'
@@ -331,8 +336,8 @@ backup-simple() {
 		"${source%\/}"/
 		"${target%\/}"/
 	)
-	printf '%q ' "${cmd[@]}"; printf '\n'
-	"${cmd[@]}"
+	printf '%q ' "${cmdarr[@]}"; printf '\n'
+	"${cmdarr[@]}"
 }
 
 # 1337!
@@ -353,8 +358,8 @@ sudo-function() {
 }
 super-sudo() {
 	(($#)) || { echo "Usage: super-sudo CMD [ARGS...]" >&2; return 1; }
-	local def ftype; ftype=$(type -t $1) ||
-	{ echo "not found: $1" >&2; return 1; }
+	local def ftype; ftype=$(type -t "$1") ||
+		{ echo "not found: $1" >&2; return 1; }
 	if [[ "$ftype" == "function" ]]; then def=$(declare -f "$1")
 	else def=$(declare -p PATH); fi  # file or builtin
 	sudo bash -c "${def};$(printf ' %q' "$@")"
@@ -393,6 +398,7 @@ complete-copy() {
 	local cmd="$1"
 	shift
 	if complete -p "$cmd" &>/dev/null && type "$@" &>/dev/null; then
+		# shellcheck disable=SC2046
 		eval $(complete -p "$cmd") "$@"
 	fi
 }
@@ -400,7 +406,7 @@ complete-copy() {
 # See /usr/share/bash-completion/completions/apt-cache._apt_cache_packages()
 _comp_pkg_names() {
 	local cur; _get_comp_words_by_ref cur
-	COMPREPLY=( $(apt-cache --no-generate pkgnames -- "$cur" 2>/dev/null) )
+	mapfile -t COMPREPLY < <(apt-cache --no-generate pkgnames -- "$cur" 2>/dev/null)
 	return 0
 }
 
@@ -418,7 +424,8 @@ complete-copy dwww-man mand manc
 # Alternative: \${?/#0/} directly into PS1, but lacks surrounding spaces
 _format_exitcode() {
 	local s=$?
-	if (($s)); then printf "${1:-%s }" "$s"; fi
+	# shellcheck disable=SC2059
+	if ((s)); then printf "${1:-%s }" "$s"; fi
 	return $s
 }
 
@@ -445,6 +452,7 @@ if ! exists __git_ps1; then
 		__git_ps1() {
 			local s=$?
 			if exists git; then
+				# shellcheck disable=SC2063
 				git branch 2>/dev/null |
 				grep '^*' |
 				sed 's/* \(.*\)/\1 /'
@@ -476,6 +484,7 @@ declare -A c=(
 # PS2='> '
 
 # Final product
+# shellcheck disable=SC2140
 PS1="${c[RESET]}${c[BOLD]}"\
 "${c[PURPLE]}\t ${c[CYAN]}\$(_shell_level)${c[GREEN]}\u@\h ${c[BLUE]}\w "\
 "${c[RED]}\$(__git_ps1 '%s ')${c[YELLOW]}\$(_format_exitcode)${c[RED]}\\$ "\
@@ -496,6 +505,7 @@ paths=(
 	"${HOME}/.bash_aliases_local"
 )
 for path in "${paths[@]}"; do
+	# shellcheck source=./.bash_aliases_local
 	if [[ -r "$path" ]]; then source "$path"; fi
 done
 unset paths path
