reference: improve and update template, commonlib

diff --git a/reference/template b/reference/template
--- a/reference/template
+++ b/reference/template
@@ -2,7 +2,7 @@
 #
 # progname - short description
 #
-#    Copyright (C) 2022 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
+#    Copyright (C) 2023 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -25,7 +25,7 @@
 # progname - short description
 #
 # This file is part of [PROJNAME], see <https://github.com/MestreLion/[PROJTAG]>
-# Copyright (C) 2022 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
+# Copyright (C) 2023 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
 # License: GPLv3 or later, at your choice. See <http://www.gnu.org/licenses/gpl>
 #------------------------------------------------------------------------------
 
@@ -38,8 +38,8 @@ verbose=0
 
 #------------------------------------------------------------------------------
 
-myname=${0##*/}
-mydir=$(dirname "$(readlink -f "$0")")
+myself=${0##*/}
+here=$(dirname "$(readlink -f "$0")")
 
 #------------------------------------------------------------------------------
 
@@ -49,11 +49,11 @@ green()   { tput setaf 2; bold "$@"; }
 fatal()   { if (($#)); then { red "$@"; echo; } >&2; fi; exit 1; }
 message() { if (($# && verbose)); then green '* ' "$@"; echo; fi; }
 
-fatal()   { if (($#)); then echo "$myname: error: $1" >&2; fi; exit ${2:-1}; }
-fatal()   { if (($#)); then echo "$myname: error: $@" >&2; fi; exit 1; }
+fatal()   { if (($#)); then echo "$myself: error: $1" >&2; fi; exit ${2:-1}; }
+fatal()   { if (($#)); then echo "$myself: error: $@" >&2; fi; exit 1; }
 message() { if (($# && verbose)); then printf '%s\n' "$@"; fi; }
 
-argerr()  { printf "%s: %s\n" "$myname" "${1:-error}" >&2; usage 1; }
+argerr()  { printf "%s: %s\n" "$myself" "${1:-error}" >&2; usage 1; }
 invalid() { argerr "invalid ${2:-option}: ${1:-}"; }
 missing() { argerr "missing ${1:+$1 }argument${2:+ from $2}."; }
 
@@ -97,11 +97,11 @@ require() {
 usage() {
 	if [[ "${1:-}" ]] ; then exec >&2; fi
 	cat <<-USAGE
-	Usage: $myname [options]
+	Usage: $myself [options]
 	USAGE
 	if [[ "${1:-}" ]] ; then
 		cat <<- USAGE
-		Try '$myname --help' for more information.
+		Try '$myself --help' for more information.
 		USAGE
 		exit 1
 	fi
