reference: apply ShellCheck suggestions

diff --git a/reference/template b/reference/template
--- a/reference/template
+++ b/reference/template
@@ -35,6 +35,7 @@ trap '>&2 echo "error: line $LINENO, status $?: $BASH_COMMAND"' ERR
 #------------------------------------------------------------------------------
 
 verbose=0
+opt=default
 
 #------------------------------------------------------------------------------
 
@@ -49,8 +50,8 @@ green()   { tput setaf 2; bold "$@"; }
 fatal()   { if (($#)); then { red "$@"; echo; } >&2; fi; exit 1; }
 message() { if (($# && verbose)); then green '* ' "$@"; echo; fi; }
 
-fatal()   { if (($#)); then echo "$self: error: $1" >&2; fi; exit ${2:-1}; }
-fatal()   { if (($#)); then echo "$self: error: $@" >&2; fi; exit 1; }
+fatal()   { if (($#)); then echo "$self: error: $1" >&2; fi; exit "${2:-1}"; }
+fatal()   { if (($#)); then echo "$self: error: $*" >&2; fi; exit 1; }
 message() { if (($# && verbose)); then printf '%s\n' "$@"; fi; }
 
 argerr()  { printf "%s: %s\n" "$self" "${1:-error}" >&2; usage 1; }
@@ -65,11 +66,12 @@ numeric() { [[ "$1" ]] || missing "${3-NUM}" "${2:-}"; local re='^[0-9]+([.][0-9
 integer() { [[ "$1" ]] || missing "${3:-NUM}" "${2:-}"; [[ "$1" != *[!0-9]* ]] ||
             argerr "${2:+${3:-NUM} argument in $2 is }not an integer: $1"; }
 sizefmt() { [[ "$1" ]] || missing "${3:-SIZE}" "${2:-}";
-            echo $(numfmt --from=auto -- "$1" || fatal); }
+            numfmt --from=auto -- "$1" || fatal; }
 si()      { numfmt --to=si --suffix 'B' "$@"; }
 relpath() { python3 -c "import os,sys;print(os.path.relpath(*sys.argv[1:3]))" "$@"; }
 cmdpath() { type -P "$1"; }
 escape()  { printf '%q' "$@"; }  # perhaps change to $1, as $@ will not work as expected
+# shellcheck disable=SC2104
 skip()    { i=${2:-$file}; message "skipping${i:+ $i}${1:+: $1}"; continue ; }
 quit()    { message "Goodbye!"; exit; }
 require() {
@@ -127,6 +129,7 @@ for arg in "$@"; do
 done
 args=()
 while (($#)); do
+	# shellcheck disable=SC2221,SC2222
 	case "$1" in
 	-v|--verbose) verbose=1;;
 	-o|--opt) shift; opt=${1:-};;
@@ -149,14 +152,16 @@ esac
 
 #------------------------------------------------------------------------------
 
-[[ "${var:-}" ]] || missing "ARG" "--var"
+[[ "${opt:-}" ]] || missing "OPT" "--opt"
 integer "${count:-}" '--count'
 size=$(sizefmt "${size:-}" '--size') || exit
 
 #------------------------------------------------------------------------------
 
-echo "var=${var:-}"
-((${#files[@]})) &&  echo "files: ${files[@]}"
+echo "$self running from $here"
+echo "opt=${opt:-}"
+((${#opts[@]})) &&  echo "opts: " "${opts[@]}"
+((${#args[@]})) &&  echo "args: " "${args[@]}"
 
 tmpdir=$(mktemp --directory) || fatal "could not create temp dir"
 trap 'rm -rf -- "$tmpdir"' EXIT
