reference/template: be friendly with bash -u

diff --git a/reference/template b/reference/template
--- a/reference/template
+++ b/reference/template
@@ -24,12 +24,14 @@ myname="${0##*/}"
 mydir=$(dirname "$(readlink -f "$0")")
 verbose=0
 
-fatal()   { [[ "$1" ]] && echo "$myname: error: $1" >&2 ; exit ${2:-1} ; }
-message() { ((verbose)) && printf "%s\n" "$1"; }
-integer() { [[ "$1" != *[!0-9]* ]] || argerr "'$1'${2:+ in $2} is not an integer." ; }
+fatal()   { [[ "${1:-}" ]] && echo "$myname: error: $@" >&2 ; exit 1; }
+fatal()   { [[ "${1:-}" ]] && echo "$myname: error: $1" >&2 ; exit ${2:-1} ; }
+message() { if ((verbose)); then printf "%s\n" "${1:-}"; fi; }
+integer() { [[ "${1:-}" != *[!0-9]* ]] ||
+            argerr "'${1:-}'${2:+ in $2} is not an integer." ; }
 skip()    { i=${2:-$file}; message "skipping${i:+ $i}${1:+: $1}"; continue ; }
 argerr()  { printf "%s: %s\n" "$myname" "${1:-error}" >&2 ; usage 1 ; }
-invalid() { argerr "invalid option: $1" ; }
+invalid() { argerr "invalid option: ${1:-}" ; }
 missing() { argerr "missing ${2:+$2 }argument${1:+ from $1}." ; }
 quit()    { message "Goodbye!" ; exit; }
 relpath() { python -c "import os, sys; print os.path.relpath(*sys.argv[1:3])" "$@"; }
@@ -39,7 +41,7 @@ usage() {
 	cat <<-USAGE
 	Usage: $myname [options]
 	USAGE
-	if [[ "$1" ]] ; then
+	if [[ "${1:-}" ]] ; then
 		cat >&2 <<- USAGE
 		Try '$myname --help' for more information.
 		USAGE
