setup/git: use ~/.config/git to store settings

diff --git a/setup/setup/git.install b/setup/setup/git.install
--- a/setup/setup/git.install
+++ b/setup/setup/git.install
@@ -1,14 +1,34 @@
 #!/bin/bash
 
-config=${XDG_CONFIG_HOME:-$HOME/.config}/git/config
-#template=${SCRIPTS:-$(readlink -f "$(dirname "$(readlink -f "$0")")/../..")}/git_template
+# -----------------------------------------------------------------------------
 
-mkdir -p -- "${config%/*}"
+setuplib=${1:-${SETUP_LIB:-$(dirname "$(readlink -f "$0")")/../setuplib}}
+
+usage() { echo "Usage: [SCRIPTS=<DIR>] ${0##*/} [SETUP_LIB]" >&2; exit 1; }
+
+if [[ -r "$setuplib" ]]; then
+	source "$setuplib"
+else
+	echo "Setup library not found! $setuplib" >&2
+	usage
+fi
+
+# -----------------------------------------------------------------------------
+
+gitdir=${XDG_CONFIG_HOME:-$HOME/.config}/git
+
+config=$gitdir/config
+templatedir=$gitdir/template
+
+source=${SCRIPTS:-$(readlink -f "$(dirname "$(readlink -f "$0")")/../..")}/git_template
+
+mkdir -p -- "$gitdir"
+
+if ! [[ -d "$templatedir" ]]; then
+	ln -s -- "$(relpath "$source" "$gitdir")" "$templatedir"
+fi
 
 if ! [[ -f "$config" ]]; then
-	if [[ -z "$SCRIPTS" ]]; then
-		echo "\$SCRIPTS is not set! Git template dir won't work until scripts are installed" >&2
-	fi
 	cat > "$config" <<-EOF
 		[user]
 		name = MestreLion
@@ -25,7 +45,7 @@ if ! [[ -f "$config" ]]; then
 		whitespace = fix
 
 		[init]
-		templatedir = \$SCRIPTS/git_template
+		templatedir = ${templatedir/#$HOME/\~}
 
 		[credential]
 		helper = cache --timeout=604800
